#!/bin/sh -u
targetDir="$1"

type objdump || exit 1

find "$targetDir" -xdev ! -name libvirtcpuid.so -type f | while read -r elf; do
    tmp="$elf.$(basename -- "$0").tmp"
    rm -f "$tmp"
    objdump --prefix-addresses --show-raw-insn --file-offsets -d "$elf" 2>/dev/null | grep -E '\s0f a2\s+cpuid\s*$' | grep -oE '\(File Offset: 0x[^)]+' | cut -d: -f2 |
        while read -r offset; do
            if ! test -e "$tmp"; then
                if test -x "$elf" && ! readelf -l "$elf" | grep -qF '[Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]'; then
                    echo "Warning: Cannot patch $elf" >&2
                    break
                fi
                echo "Patching $elf"
                # Work around "Text file busy"
                cp "$elf" "$tmp"
            fi
            printf "$(printf '\\%o' 0x0f 0x32)" | dd of="$tmp" bs=1 seek="$(($offset))" conv=notrunc status=none
        done
    if test -e "$tmp"; then mv "$tmp" "$elf"; fi
done
